/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cetcme_radiostation_JniUtils */

#ifndef _Included_com_cetcme_radiostation_JniUtils
#define _Included_com_cetcme_radiostation_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cetcme_radiostation_JniUtils
 * Method:    VoiceEncode
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_cetcme_radiostation_JniUtils_VoiceEncode
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_cetcme_radiostation_JniUtils
 * Method:    VoiceDecode
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_cetcme_radiostation_JniUtils_VoiceDecode
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
